[exhentai]
href = 'https://e-hentai.org/?f_cats=1001&f_search=chinese&inline_set=dm_t&page='
launchArgs = ['--proxy-server=127.0.0.1:12333']
headless = true
winChromePath = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'
linuxChromePath = '/opt/google/chrome/chrome'
waitTime = 1000
maxPageIndex = 40
downloadPath = 'exhentai'
proxy = 'http://127.0.0.1:12333'
# size, normal is gdtm, large is gdtl
thumbnailClass = '.gdtm a'
listInfoPath = 'src/assets/exhentai/'

[log]
dateFormat = 'yyyy-MM-dd HH:mm:ss'

[document]
mappingFilePath = 'src/assets/mapping.json'
